inclusion_criteria_21_283 = [
    "The patient or a legally authorized representative must provide study-specific informed consent prior to pre entry /step 1 and, for patients treated in the U.S., authorization permitting release of personal health information",
    "The patient must be ≥ 50 years and < 70 years of age.",
    "The trial is open to female and male patients.",
    "The patient must have an ECOG performance status of 0 or 1.",
    "The patient must have undergone a lumpectomy and the margins of the resected specimen or re-excision must be histologically free of invasive tumor and DCIS with no ink on tumor as determined by the local pathologist. If pathologic examination demonstrates tumor at the line of resection, additional excisions may be performed to obtain clear margins. (Patients with margins positive for LCIS are eligible without additional resection.",
    "The tumor must be unilateral invasive adenocarcinoma of the breast on histologic examination",
    "Patient must have undergone axillary staging (sentinel node biopsy and/or axillary node dissection).",
    "The following staging criteria must be met postoperatively according to AJCC 8th edition criteria: By pathologic evaluation, primary tumor must be pT1 ( ≤ 2 cm). By pathologic evaluation, ipsilateral nodes must be pN0. (Patients with pathologic staging of pN0(i+) or pN0(mol+) are NOT eligible.)",
    "The tumor must have been determined to be ER and/or PgR positive assessed by current ASCO/CAP Guideline Recommendations for hormone receptor testing. Patients with ≥ 1% ER or PgR staining by IHC are considered positive",
    "The tumor must have been determined to be HER2-negative by current ASCO/CAP guidelines",
    "Patients may be premenopausal or postmenopausal at the time of pre-entry/Step 1. For study purposes, postmenopausal is defined as: (YES / NA)  Age 56 or older with no spontaneous menses for at least 12 months prior to pre-entry/Step 1; or a documented hysterectomy; or  Age 55 or younger with no spontaneous menses for at least 12 months prior to pre entry/ Step 1(e.g., spontaneous or secondary to hysterectomy) and with a documented estradiol level in the postmenopausal range according to local institutional/laboratory standard; or Documented bilateral oophorectomy.",
    "The interval between the last surgery for breast cancer (including re-excision of margins) and pre-entry/Step 1 must be no more than 70 days",
    "The patient must have recovered from surgery with the incision completely healed and no signs of infection.",
    "Bilateral mammogram or MRI within 6 months prior to study entry",
    "HIV-infected patients on effective anti-retroviral therapy with undetectable viral load within 6 months are eligible for this trial",
    "Patients must be intending to take endocrine therapy for a minimum 5 years duration (tamoxifen or aromatase inhibitor). The specific regimen of endocrine therapy is at the treating physician's discretion.",
    "Has the patient seen their Medical Oncologist?",
]
exclusion_criteria_21_283 = [
    "Definitive clinical or radiologic evidence of metastatic disease.",
    "pT1mi and pT2 - pT4 tumors including inflammatory breast cancer.",
    "Pathologic staging of pN0(i+) or pN0(mol+), pN1, pN2, or pN3 disease.",
    "Patient had a mastectomy.",
    "Palpable or radiographically suspicious ipsilateral or contralateral axillary, supraclavicular, infraclavicular, or internal mammary nodes, unless there is histologic confirmation that these nodes are negative for tumor",
    "Suspicious microcalcifications, densities, or palpable abnormalities (in the ipsilateral or contralateral breast) unless biopsied and found to be benign",
    "Non-epithelial breast malignancies such as sarcoma or lymphoma",
    "Proven multicentric carcinoma (invasive cancer or DCIS) in more than one quadrant or separated by 4 or more centimeters. (Patients with multifocal carcinoma are eligible.)",
    "Paget's disease of the nipple.",
    "Any history, not including the index cancer, of ipsilateral invasive breast cancer or ipsilateral DCIS treated or not treated. (Patients with synchronous or previous ipsilateral LCIS are eligible.)",
    "Synchronous or previous contralateral invasive breast cancer or DCIS. (Patients with synchronous and/or previous contralateral LCIS are eligible.)",
    "Surgical margins that cannot be microscopically assessed or are positive at pathologic evaluation. (If surgical margins are rendered free of disease by re-excision, the patient is eligible.)",
    "Treatment plan that includes regional nodal irradiation.",
    "Any treatment with radiation therapy, chemotherapy or biotherapy, and/or administered for the currently diagnosed breast cancer prior to pre- entry/Step 1.",
    "History of non-breast malignancies (except for in situ cancers treated only by local excision and basal cell and squamous cell carcinomas of the skin) within 5 years prior to study entry.",
    "Current therapy with any endocrine therapy such as raloxifene (Evista®), tamoxifen, or other selective estrogen receptor modulators (SERMs), either for osteoporosis or breast cancer prevention. (Patients are eligible for BR007 if they receive a short course of preoperative endocrine therapy of < 6 weeks duration(prior to randomization/Step 2) for this diagnosis after the core biopsy and can continue postoperatively.",
    "Patients intending to continue on oral, transdermal, or subdermal estrogen replacement (including all estrogen only and estrogen-progesterone formulas) are not eligible. Patients that discontinue oral, transdermal, or subdermal estrogen replacement prior to registration are eligible.",
    "Prior breast or thoracic RT for any condition.",
    "Active collagen vascular disease, specifically dermatomyositis with a CPK level above normal or with an active skin rash, systemic lupus erythematosis, or scleroderma.",
    "Pregnancy or lactation at the time of pre entry /Step 1 or intention to become pregnant during treatment. (Note: Pregnancy testing according to institutional standards for women of childbearing potential must be performed within 2 weeks prior to pre-entry/Step 1.)",
    "Any other disease, metabolic dysfunction, physical examination finding, or clinical laboratory finding giving reasonable suspicion of a disease or condition that contraindicates the use of study therapy or that may affect the interpretation of the results or render the patient at high risk from treatment complications.",
    "Psychiatric or addictive disorders or other conditions that, in the opinion of the investigator, would preclude the patient from meeting the study requirements or interfere with interpretation of study results.",
]

criteria_21_283 = {
    "inclusion": inclusion_criteria_21_283,
    "exclusion": exclusion_criteria_21_283,
}
